SDL InputManager - keyboard inputs
focus-fire/sad pull request #11
Opened 2022-10-09 08:44 UTC by Kotailri

### Description
Added detection for keyboard inputs including key held, key pressed, and key released

### Trello Ticket
https://trello.com/c/1l91Ao3J/30-detection-for-if-a-keyboard-key-is-pressed-held-or-released

2022-10-18 19:23 UTC, jake-pauls commented on Code/Engine/InputManager.cpp
> +                    spdlog::info("CONTROLLER LEFT");
Preferably use `core::Log(ELogType::Info, "CONTROLLER LEFT");`
Same with the others here, just quick comment updates so they dump to the new logger!

2022-10-18 19:55 UTC, jake-pauls requested changes
Only changes would be what we agreed upon in class regarding decoupling for ECS. Otherwise it looks great!

- Empty the `PlayerControllerComponent` 
- Remove the dependency on a `Transform` in the `PlayerController`
- Use entt to have the `PlayerController` perform its same operations on all entities with a `TransformComponent` and a `PlayerControllerComponent`

2022-10-21 06:32 UTC, jake-pauls approved these changes

2022-10-21 06:32 UTC, jake-pauls commented
LGTM 🚀

2022-10-21 07:22 UTC, kiwon132445 approved these changes

2022-10-21 08:06 UTC, merged