PlayerControllerSystem player and editor control component separation
focus-fire/sad pull request #23
Opened 2022-11-04 01:07 UTC by Kotailri

### Description
Separated PlayerControllerComponent into PlayerControllerComponent and EditorControllerComponent and made the PlayerControllerSystem query entities with either of those components to run their specific movement operations.

### Trello Ticket
https://trello.com/c/7gEPHOtP/48-make-a-query-in-playercontroller-for-editorcontrollercomponents

### Additional Info
PlayerController was renamed to PlayerControllerSystem and moved into the ecs systems folder, so all the PlayerControllerSystem includes were also modified.

2022-11-04 01:55 UTC, jake-pauls requested changes
Nice! Excited this is on the way - helps a lot with nailing more editor code this weekend. 🚀 

Just added some comments for things that may tighten this up a bit - also some comments are questions for preferences on how we handle some things going forward. Let me know what you think!

2022-11-04 01:55 UTC, jake-pauls commented on Code/Engine/ECS/Systems/PlayerControllerSystem.h
> +		~PlayerControllerSystem();
Do we need to have constructors and destructors defined if all methods on the system are `static`?

2022-11-04 01:55 UTC, jake-pauls commented on Code/Engine/ECS/Systems/PlayerControllerSystem.h
> +		static void Update();
What do you think about passing a reference to the `EntityWorld&` in our system updates?

Do you know if it's better to pass by reference (and have a reference in the system) or call `ecs::Registry::GetEntityWorld()` each time we want the world in each method of the system?

2022-11-04 01:55 UTC, jake-pauls commented on Code/Engine/ECS/Systems/PlayerControllerSystem.cpp
> +	float movespeed = 0.005f;
Prefer lowerCamelCase :peepobet:

2022-11-04 01:55 UTC, jake-pauls commented on Code/Engine/ECS/Systems/PlayerControllerSystem.cpp
> +	auto editorView = world.view<const sad::ecs::EditorControllerComponent, const sad::ecs::TransformComponent>();
Not too sure about any performance differences here, but we might be able to make use of a cool entt feature called `exclude`.

In this case, we make the assumption that only one of these controllers should exist at a time - so we can exclude the opposite component in both view query (ie: exclude the `EditorControllerComponent` in our search for the `PlayerControllerComponent`). Might also be good just to be really explicit with the fact that their existence is mutual so we don't accidentally update both at once 😵 . 

An example from the entt crash course!

![image](https://user-images.githubusercontent.com/48817786/199865208-d32f0dbe-eef7-4be8-841a-a22bc3308384.png)

2022-11-04 01:55 UTC, jake-pauls commented on Code/Engine/ECS/Systems/PlayerControllerSystem.cpp
> +	bool usingController = false; // bool that disables movement keys when joystick being used to prevent double speed
Does this have to be determined by the system? Could we query this from the input manager - where we just toggle it whenever a controller/keyboard event is detected? 

For instance...
```
if (input.IsControllerActive())
{
    // Check controller inputs
}
else
{
    // Check other inputs
}
```

We already use an `m_ControllerIsActive` boolean in the InputManager which could be leveraged for this... (we could check for duplicate controllers in the `InputManager::OnControllerConnected` by checking `if (m_Controller)` instead)
```
void CatchControllerEvents(...)
{
    if (sdl detects controller event)
    {
        m_ControllerIsActive = true;
    }
}

void CatchKeyboardEvents(...)
{
    if (sdl detects keyboard event)
    {
        m_ControllerIsActive = false;
    }
}

bool IsControllerActive() { return m_ControllerIsActive; }
```

2022-11-04 01:55 UTC, jake-pauls commented on Code/Engine/ECS/Components/EditorControllerComponent.h
> +}
I remember I mentioned separating components in files 😅 but now I'm wondering if it makes sense to combine the editor and player controller components in one file? I'm cool with joining components in the same `.h` that are manipulated by the same ECS system - just curious what you think.

Also, would probably good to add an `@brief` just explaining what the component does 😄

2022-11-04 02:17 UTC, jake-pauls commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make a query in PlayerController for EditorControllerComponent(s)](https://trello.com/c/7gEPHOtP/48-make-a-query-in-playercontroller-for-editorcontrollercomponents)

2022-11-04 06:00 UTC, Kotailri reviewed
Oops i mistyped in a commit, its "conflict from using keyboard and ~~keyboard~~ controller"

2022-11-06 21:37 UTC, jake-pauls approved these changes
Looking good! 🚀

2022-11-07 03:23 UTC, paulc100 approved these changes

2022-11-07 04:52 UTC, merged