Audio Manager
focus-fire/sad pull request #27
Opened 2022-11-07 04:17 UTC by keithliu03

### Description
We now have a way to play audio/sfx.

### Trello Ticket
[Add the URL to the most applicable ticket on the [Trello](https://trello.com/b/fKcBhH3P/game-engine-development) board.](https://trello.com/c/05NsGYh5)

### Additional Info
Have not implemented audio manager into anything in the latest dev branch. Has been tested and does work with an outdated dev, and will implement once latest pull requests are done.

2022-11-07 04:31 UTC, RaziqK approved these changes

2022-11-07 08:12 UTC, jake-pauls requested changes
Awesome! Love that sound is in.

Left some comments for integrating this with the new `ResourceManager` features that will really cut this down. Make sure to pull latest to get the new `AudioResource`.

2022-11-07 08:12 UTC, jake-pauls commented on Code/Engine/AudioManager.h
> +        static void set_volume(std::string filename, int volume);
Style guide

- `UpperCamelCase` for method names
- `lowerCamelCase` for variable names (ie: `fileName`)

2022-11-07 08:12 UTC, jake-pauls commented on Code/Engine/AudioManager.cpp
> +    core::Log(ELogType::Debug, "Audio Path: {}", path.c_str()); // Debug Path
Is this log necessary?

Prefer using `Info`, `Trace` or `Warn` logging channels if the logs being added are meant to be permanent/informational.

2022-11-07 08:12 UTC, jake-pauls commented on Code/Engine/AudioManager.cpp
> +    }
It looks like this is akin to SDL initialization code - we can probably move this check to `Window.cpp` as it only has to be done once and not for every audio file.

Namely, we should add `SDL_INIT_AUDIO` into the `SDL_Init` call on line 14 (recommended by the link below).
This method/check can then be added in the `sad::Window::Start` method with an assert.

Something like...
```
int mixerInitialization = Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 512);
SAD_ASSERT(mixerInitialization >= 0, "Failed to open audio device for SDL_Mixer");
```

https://wiki.libsdl.org/SDL_mixer/Mix_OpenAudio

2022-11-07 08:12 UTC, jake-pauls commented on Code/Engine/AudioManager.cpp
> +        }
We can probably make this super efficient and clean by leveraging the new ResourceManager.

I've already made an `AudioResource.cpp` that will have a handful of these settings automatically generated such as file name, path, and extension. What we can do is move the audio-file specific initialization code (such as mixing the volume chunks) to there and remove the static list of audio files in the audio manager.

In that sense, the `AudioManager` could just take a single `AudioResource` as most of the parameters (removing the static list and need for loops 🆒 ) here (ie for `SetVolume` or `PlaySFX`) and just play what's already been created for the audio resource by the resource manager.

Converted methods with `AudioResource` might look something like...
```
void sad::AudioManager::PlaySFX(const AudioResource& audioResource)
{
    if (Mix_Playing(-1) == 0)
    {
        Mix_PlayChannel(-1, audioResource.MixChunk, 0);
    }
} 
```

Playing an audio resource (in a script - when it comes 😄 ) or 'on the fly' would end up looking like this...
```
AudioResource* audioResource = ResourceManager::GetResource<AudioResource>("Code_Arabic_Nokia.wav");
AudioManager::GetInstance().PlaySFX(audioResource);
```

2022-11-07 08:45 UTC, jake-pauls commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create a sample AudioManager that can play, stop, and pause audio with SDL](https://trello.com/c/05NsGYh5/27-create-a-sample-audiomanager-that-can-play-stop-and-pause-audio-with-sdl)

2022-11-07 10:26 UTC, kiwon132445 approved these changes

2022-11-08 09:31 UTC, jake-pauls approved these changes

2022-11-08 10:15 UTC, merged